# Generated by Django 5.2 on 2026-02-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_carlistingimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showroom",
            fields=[
                ("showroom_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("state", models.CharField(max_length=80)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("map_query", models.CharField(blank=True, help_text="Query string used for Google Maps search", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="showrooms", to="core.user")),
            ],
        ),
        migrations.CreateModel(
            name="UpcomingArrival",
            fields=[
                ("arrival_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("make", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("expected_date", models.DateField()),
                ("status", models.CharField(choices=[("Announced", "Announced"), ("Delayed", "Delayed"), ("Cancelled", "Cancelled")], default="Announced", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("showroom", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="arrivals", to="core.showroom")),
            ],
        ),
    ]
