# Generated by Django 5.2 on 2026-02-24

from django.db import migrations

def seed_showrooms(apps, schema_editor):
    Showroom = apps.get_model("core", "Showroom")
    seeds = [
        {"name": "Maruti Suzuki Arena", "city": "Vadodara", "state": "Gujarat", "address": "Akota", "map_query": "Maruti Suzuki Arena Akota Vadodara"},
        {"name": "Nexa Showroom", "city": "Vadodara", "state": "Gujarat", "address": "Alkapuri", "map_query": "Nexa Alkapuri Vadodara"},
        {"name": "Hyundai Showroom", "city": "Vadodara", "state": "Gujarat", "address": "Old Padra Road", "map_query": "Hyundai Showroom Old Padra Road Vadodara"},
        {"name": "Audi Ahmedabad", "city": "Ahmedabad", "state": "Gujarat", "address": "SG Highway", "map_query": "Audi showroom SG Highway Ahmedabad"},
        {"name": "Nexa Ahmedabad", "city": "Ahmedabad", "state": "Gujarat", "address": "CG Road", "map_query": "Nexa CG Road Ahmedabad"},
        {"name": "Hyundai Ahmedabad", "city": "Ahmedabad", "state": "Gujarat", "address": "Satellite", "map_query": "Hyundai Showroom Satellite Ahmedabad"},
        {"name": "BMW Deutsche Motoren", "city": "Mumbai", "state": "Maharashtra", "address": "Worli", "map_query": "BMW showroom Worli Mumbai"},
        {"name": "Toyota Lakozy", "city": "Mumbai", "state": "Maharashtra", "address": "Andheri", "map_query": "Toyota showroom Andheri Mumbai"},
        {"name": "Audi Mumbai West", "city": "Mumbai", "state": "Maharashtra", "address": "Andheri West", "map_query": "Audi Mumbai West Andheri"},
        {"name": "NEXA Connaught Place", "city": "Delhi", "state": "Delhi", "address": "Connaught Place", "map_query": "NEXA Connaught Place Delhi"},
        {"name": "Hyundai Dwarka", "city": "Delhi", "state": "Delhi", "address": "Dwarka", "map_query": "Hyundai showroom Dwarka Delhi"},
        {"name": "Mercedes-Benz T&T Motors", "city": "Delhi", "state": "Delhi", "address": "Mathura Road", "map_query": "Mercedes Benz T&T Motors Mathura Road Delhi"},
        {"name": "Toyota Pune", "city": "Pune", "state": "Maharashtra", "address": "Wakad", "map_query": "Toyota showroom Wakad Pune"},
        {"name": "Nexa Pune", "city": "Pune", "state": "Maharashtra", "address": "Baner", "map_query": "Nexa showroom Baner Pune"},
        {"name": "Hyundai Pune", "city": "Pune", "state": "Maharashtra", "address": "Kharadi", "map_query": "Hyundai showroom Kharadi Pune"},
        {"name": "Nexa Bengaluru", "city": "Bengaluru", "state": "Karnataka", "address": "Indiranagar", "map_query": "Nexa showroom Indiranagar Bengaluru"},
        {"name": "Hyundai Bengaluru", "city": "Bengaluru", "state": "Karnataka", "address": "Koramangala", "map_query": "Hyundai showroom Koramangala Bengaluru"},
        {"name": "Audi Bengaluru", "city": "Bengaluru", "state": "Karnataka", "address": "Richmond Road", "map_query": "Audi showroom Richmond Road Bengaluru"},
        {"name": "Hyundai Chennai", "city": "Chennai", "state": "Tamil Nadu", "address": "OMR", "map_query": "Hyundai showroom OMR Chennai"},
        {"name": "Nexa Chennai", "city": "Chennai", "state": "Tamil Nadu", "address": "T Nagar", "map_query": "Nexa showroom T Nagar Chennai"},
        {"name": "BMW Chennai", "city": "Chennai", "state": "Tamil Nadu", "address": "Mount Road", "map_query": "BMW showroom Mount Road Chennai"},
        {"name": "Nexa Hyderabad", "city": "Hyderabad", "state": "Telangana", "address": "Banjara Hills", "map_query": "Nexa showroom Banjara Hills Hyderabad"},
        {"name": "Hyundai Hyderabad", "city": "Hyderabad", "state": "Telangana", "address": "Kukatpally", "map_query": "Hyundai showroom Kukatpally Hyderabad"},
        {"name": "Audi Hyderabad", "city": "Hyderabad", "state": "Telangana", "address": "Madhapur", "map_query": "Audi showroom Madhapur Hyderabad"},
        {"name": "NEXA Kolkata", "city": "Kolkata", "state": "West Bengal", "address": "Park Street", "map_query": "NEXA showroom Park Street Kolkata"},
        {"name": "Hyundai Kolkata", "city": "Kolkata", "state": "West Bengal", "address": "Salt Lake", "map_query": "Hyundai showroom Salt Lake Kolkata"},
        {"name": "BMW Kolkata", "city": "Kolkata", "state": "West Bengal", "address": "EM Bypass", "map_query": "BMW showroom EM Bypass Kolkata"},
        {"name": "NEXA Jaipur", "city": "Jaipur", "state": "Rajasthan", "address": "Tonk Road", "map_query": "NEXA showroom Tonk Road Jaipur"},
        {"name": "Hyundai Jaipur", "city": "Jaipur", "state": "Rajasthan", "address": "Vaishali Nagar", "map_query": "Hyundai showroom Vaishali Nagar Jaipur"},
        {"name": "Audi Jaipur", "city": "Jaipur", "state": "Rajasthan", "address": "Ajmer Road", "map_query": "Audi showroom Ajmer Road Jaipur"},
    ]
    for d in seeds:
        Showroom.objects.get_or_create(
            name=d["name"], city=d["city"], state=d["state"],
            defaults={"address": d["address"], "map_query": d["map_query"]}
        )

def unseed_showrooms(apps, schema_editor):
    Showroom = apps.get_model("core", "Showroom")
    Showroom.objects.filter(map_query__icontains="showroom").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_showroom_arrival"),
    ]

    operations = [
        migrations.RunPython(seed_showrooms, unseed_showrooms),
    ]
