# Generated by Django 5.2 on 2026-02-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_showrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="carlisting",
            name="showroom",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="car_listings", to="core.showroom"),
        ),
    ]
