# Generated by Django 5.2.11 on 2026-03-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_activitylog_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarListingAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.FileField(upload_to="listing_assets/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("3D_MODEL", "3D Model"),
                            ("PANORAMA_EXTERIOR", "Exterior Panorama"),
                            ("PANORAMA_INTERIOR", "Interior Panorama"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.carlisting",
                    ),
                ),
            ],
        ),
    ]
