# Generated by Django 5.2.11 on 2026-03-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_carlistingasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="ai_condition_score",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
