# Generated by Django 5.2.10 on 2026-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_inspection_ai_condition_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="toxicity_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
