# Generated by Django 5.2.10 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_savedsearch_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="carlisting",
            name="deal_label",
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="carlisting",
            name="import_duty",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="carlisting",
            name="insurance_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="carlisting",
            name="market_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="carlisting",
            name="on_road_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="carlisting",
            name="tax_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
