# Generated by Django 5.2.11 on 2026-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_carlisting_market_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carlistingasset",
            name="asset",
            field=models.FileField(blank=True, null=True, upload_to="listing_assets/"),
        ),
        migrations.AlterField(
            model_name="carlistingasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("3D_MODEL", "3D Model"),
                    ("PANORAMA_EXTERIOR", "Exterior Panorama"),
                    ("PANORAMA_INTERIOR", "Interior Panorama"),
                    ("SKETCHFAB", "Sketchfab Embed"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
