# Generated by Django 5.2.10 on 2026-02-27 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_activitylog_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("sales", "Recent Sales"),
                            ("inventory", "Inventory Status"),
                            ("inquiries", "Recent Inquiries"),
                            ("test_drives", "Test Drive Requests"),
                            ("messages", "Messages"),
                            ("analytics", "Analytics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_listings", models.IntegerField(default=0)),
                ("active_listings", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                ("total_inquiries", models.IntegerField(default=0)),
                ("total_test_drives", models.IntegerField(default=0)),
                ("response_rate", models.FloatField(default=0.0)),
                ("average_days_to_sell", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.seller",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dashboard Metrics",
            },
        ),
    ]
