from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    HomeView,
    CarsListView,
    BrandView,
    AllCarsListView,
    VerifyOtpView,
    ListingsListView,
    MessagesInboxView,
    TestDrivesView,
    SellStartView,
    UserSignupView,
    AccountSettingsView,
    BuyersListView,
    SellersListView,
    LogoutViewCustom,
    ListingUpdateView,
    ListingDeleteView,
    ListingCreateView,
    ListingDetailView,
    ListingImagesDeleteView,
    ListingMessageView,
    PurchaseListingView,
    UserLoginView,
    CarUpdateView,
    CarDeleteView,
    listing_specs_pdf,
    compare_export_pdf,
    PricingAnalyticsView,
    price_chart_data,
    price_trend_data,
    pricing_export_csv,
    pricing_aggregate_api,
    BuyerDetailView,
    SellerDetailView,
    RequestSellToSellerView,
    RequestBuyToBuyerView,
    ReplyToMessageView,
    AcceptDealView,
    RateUserView,
    TestDriveCreateView,
    TestDriveUpdateView,
    CitiesIndexView,
    CityShowroomsView,
    UpcomingArrivalCreateView,
    ActivityTodosView,
    ActivityMeetingView,
    ActivityHistoryView,
    EmailStatusView,
    InspectionCreateView,
    CompareCarsView,
    ChatbotView,
    ResendOtpView,
    booking,
    booke,
    create_razorpay_order,
    verify_payment,
    transactions_export,
    toggle_favorite,
    save_search,
    geo_states,
    geo_cities,
    # saved items and exports pages
    saved_items,
    account_exports,
    favorite_delete,
    saved_search_delete,
    BrochureView,
)

urlpatterns = [
    path("", HomeView, name="home"),
    path("cars/", CarsListView, name="cars"),
    path("cars/<slug:brand_slug>/", BrandView, name="brand_page"),
    path("all-cars/", AllCarsListView, name="all_cars"),
    path("cars/<str:vin>/edit/", CarUpdateView, name="car_edit"),
    path("cars/<str:vin>/delete/", CarDeleteView, name="car_delete"),
    path("listings/", ListingsListView, name="listings"),
    path("listings/<uuid:listing_id>/", ListingDetailView, name="listing_detail"),
    path("listings/<uuid:listing_id>/message/", ListingMessageView, name="listing_message"),
    path("listings/<uuid:listing_id>/purchase/", PurchaseListingView, name="listing_purchase"),
    path("listings/new/", ListingCreateView, name="listing_new"),
    path("listings/<uuid:listing_id>/edit/", ListingUpdateView, name="listing_edit"),
    path("listings/<uuid:listing_id>/delete/", ListingDeleteView, name="listing_delete"),
    path("listings/<uuid:listing_id>/images/delete/", ListingImagesDeleteView, name="listing_images_delete"),
    path("listings/<uuid:listing_id>/specs.pdf", listing_specs_pdf, name="listing_specs_pdf"),
    path("compare/export.pdf", compare_export_pdf, name="compare_export_pdf"),
    path("analytics/pricing/", PricingAnalyticsView, name="pricing_analytics"),
    path("analytics/price-chart-data/", price_chart_data, name="price_chart_data"),
    path("analytics/pricing/trend/", price_trend_data, name="price_trend_data"),
    path("analytics/pricing/export/", pricing_export_csv, name="pricing_export"),
    path("api/pricing/aggregate/", pricing_aggregate_api, name="pricing_aggregate_api"),
    path("messages/", MessagesInboxView, name="messages"),
    path("messages/<uuid:message_id>/reply/", ReplyToMessageView, name="message_reply"),
    path("messages/<uuid:message_id>/accept-deal/", AcceptDealView, name="message_accept_deal"),
    path("testdrives/", TestDrivesView, name="testdrives"),
    path("testdrives/new/", TestDriveCreateView, name="testdrive_new"),
    path("testdrives/<uuid:test_drive_id>/edit/", TestDriveUpdateView, name="testdrive_edit"),
    path("cities/", CitiesIndexView, name="cities"),
    path("cities/<slug:city_slug>/", CityShowroomsView, name="city_showrooms"),
    path("cities/arrivals/new/", UpcomingArrivalCreateView, name="arrival_new"),
    path("sell/", SellStartView, name="sell"),
    path("contact/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/contact.html"), name="contact"),
    path("faq/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/faq.html"), name="faq"),
    path("privacy/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/privacy.html"), name="privacy"),
    path("terms/", lambda r: __import__('django.shortcuts').shortcuts.render(r, "core/terms.html"), name="terms"),
    path("profiles/buyers/", BuyersListView, name="buyers"),
    path("profiles/buyers/<uuid:user_id>/", BuyerDetailView, name="buyers_detail"),
    path("profiles/buyers/<uuid:user_id>/request-buy/", RequestBuyToBuyerView, name="buyer_request_buy"),
    path("profiles/users/<uuid:user_id>/rate/", RateUserView, name="rate_user"),
    path("profiles/sellers/", SellersListView, name="sellers"),
    path("profiles/sellers/<uuid:user_id>/", SellerDetailView, name="sellers_detail"),
    path("profiles/sellers/<uuid:user_id>/request-sell/", RequestSellToSellerView, name="seller_request_sell"),
    path("signup/", UserSignupView, name="signup"),
    path("login/", UserLoginView, name="login"),
    path("verify-otp/", VerifyOtpView, name="verify_otp"),
    path("resend-otp/", ResendOtpView, name="resend_otp"),
    path("logout/", LogoutViewCustom, name="logout"),
    path("account/settings/", AccountSettingsView, name="account_settings"),
    path("activity/todos/", ActivityTodosView, name="activity_todos"),
    path("activity/meeting/", ActivityMeetingView, name="activity_meeting"),
    path("activity/history/", ActivityHistoryView, name="activity_history"),
    path("email/status/", EmailStatusView, name="email_status"),
    path("inspections/new/", InspectionCreateView, name="inspection_new"),
    path("compare/", CompareCarsView, name="compare"),
    path("chatbot/", ChatbotView, name="chatbot"),
    path("booking/", booking, name="booking"),
    path("booke/", booke, name="booke"),
    path("razorpay/order/", create_razorpay_order, name="create_razorpay_order"),
    path("razorpay/verify/", verify_payment, name="verify_payment"),
    # optional aliases matching sample naming
    path("create-order/", create_razorpay_order, name="create_order_alias"),
    path("verify-payment/", verify_payment, name="verify_payment_alias"),
    path("transactions/export/", transactions_export, name="transactions_export"),
    path("favorites/toggle/", toggle_favorite, name="toggle_favorite"),
    path("searches/save/", save_search, name="save_search"),
    path("geo/states/", geo_states, name="geo_states"),
    path("geo/cities/", geo_cities, name="geo_cities"),
    path("account/saved/", saved_items, name="saved_items"),
    path("account/exports/", account_exports, name="account_exports"),
    path("favorites/delete/<uuid:favorite_id>/", favorite_delete, name="favorite_delete"),
    path("searches/delete/<uuid:saved_search_id>/", saved_search_delete, name="saved_search_delete"),
    path("brochure/", BrochureView, name="brochure"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
        html_email_template_name="messages/password_reset.html",
        email_template_name="messages/password_reset_email.txt",
        subject_template_name="messages/password_reset_subject.txt",
    ), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]
